### ISSUE TITLE
Comments move to the same line as the following declaration

### ISSUE THREAD

**Issue by HarrisonGrodin** [shwestrick/parse-sml#36]
This code:
```sml
structure S = (* A *)
  struct
    (* B *)
    val x = 0
    (* C *)
    val y = 1
  end
(* D *)

val z = 2
```
autoformats to:
```sml
structure S =
  (* A *)
  struct
    (* B *) val x = 0
    (* C *) val y = 1
  end
(* D *) val z = 2
```
`A` is probably fine, but `B`/`C`/`D` are clearly a bit odd. I would expect at least `B` and `C` to stay where they are; not sure where `D` should go, but it probably shouldn't pull `val z` closer, at least.

**Comment by shwestrick** [comment]
Ah interesting. The prettying pass which inserts comments locally decides whether to insert above or beside the next token. This also interacts with grouping. I did a quick and dirty implementation with a simple heuristic, but this clearly needs to be revisited.

**Comment by shwestrick** [comment]
Here's a couple more examples of issues. Multiline comments are handled differently than normal comments. IIRC, the pass which inserts comments also ungroups things in some cases. We should take a close look at this.

INPUT
```sml
(** this is a multiline comment
  *)
structure A = B

(* this is a comment *)
structure C = D
```

OUTPUT
```sml
(** this is a multiline comment
  *)
structure A
  =
  B
 
(* this is a comment *) structure C = D
```

**Comment by shwestrick** [comment]
It just occurred to me that we can make our lives easier here with `Rigid`. Multiline comments  need to be ungrouped to prevent flattening. This is currently done in an adhoc way. We could instead just make them rigid. 🚀

**Comment by shwestrick** [comment]
I also have a guess that the formatting issues with comments are caused by individual comments appearing "deeply nested" within the doc structure. Adding a pass to pull comments as high up as possible (without crossing a source token) might help.

**Comment by shwestrick** [comment]
@HarrisonGrodin some progress on this. Now the formatted output looks good for these examples:

```sml
structure S =
  (* A *)
  struct
    (* B *)
    val x = 0
    (* C *)
    val y = 1
  end
(* D *)
val z = 2
 

(** this is a multiline comment
  *)
structure A = B

(* this is a comment *)
structure C = D
```

**Comment by shwestrick** [comment]
There's still one case which seems to not quite do the right thing:

INPUT
```sml
val x =
  if b then
    yah (* comment *)
  else
    nah
```

OUTPUT (max width 20, to force ungrouping for purposes of this example)
```sml
val x =
  if b then
    yah
  (* comment *)
  else
    nah
```

**Comment by HarrisonGrodin** [comment]
Wow, that looks incredible!

> There's still one case which seems to not quite do the right thing:

How bad would it be to consider this the correct behavior? Presumably,
```sml
val x =
  if b then
    (* comment *) yah
  else
    nah
```
would format to
```sml
val x =
  if b then
    (* comment *)
    yah
  else
    nah
```
Perhaps this behavior is desirable, since it gives users a simple way to understand what comments are attached to?

**Comment by shwestrick** [comment]
Yeah definitely. I'm leaning towards leaving this as the default behavior.

There are definitely people out there that prefer writing comments after expression/declarations, rather than before. So, perhaps not ideal. But good enough for now I think!

**Comment by shwestrick** [comment]
If you agree, I think we can close this issue :)

**Comment by HarrisonGrodin** [comment]
Agreed!
