### ISSUE TITLE
Format of `andalso` and `orelse`

### ISSUE THREAD

**Issue by dram** [shwestrick/parse-sml#53]
It seems that `smlfmt` does not support formating long chain of `andalso` and `orelse`, which will exceed the `-max-width` limit, e.g.:

```sml
fun main () =
  if
    1 = 1 andalso 2 = 2 andalso 3 = 3 andalso 4 = 4 andalso 5 = 5 andalso 6 = 6 andalso 7 = 7 andalso 8 = 8
  then
    print "foo\n"
  else
    print "bar\n"

**Comment by shwestrick** [comment]
I took a stab at fixing this, and pushed a fix (3b39389f85883e6562abeb341fb342f6764d8023) which better respects the max width.

New result at 80 chars max width (seems decent):
```sml
fun main () =
  if
    1 = 1 andalso 2 = 2 andalso 3 = 3 andalso 4 = 4 andalso 5 = 5 andalso 6 = 6
    andalso 7 = 7 andalso 8 = 8
  then
    print "foo\n"
  else
    print "bar\n"
```

I'm leaving this open for now though, because it sometimes puts the newline in a "bad place", e.g. here's the output for max 40 chars.
```sml
fun main () =
  if
    1 = 1 andalso 2 = 2 andalso 3 = 3
    andalso 4 = 4 andalso 5 = 5 andalso 6
    = 6
    andalso 7 = 7 andalso 8 = 8
  then
    print "foo\n"
  else
    print "bar\n"
```

(This is a tricky issue to solve!)

**Comment by dram** [comment]
Thank you for your quick fix, @shwestrick.

It seems that after those changes, follow code will be formatted with max width exceeded:

```sml
fun main () =
  let
    val foo =
      "01234567890123456789012345678901234567890123456789" ^ "01234567890123456789012345678901234567890123456789"
      ^ "01234567890123456789012345678901234567890123456789"
  in
    print foo
  end
```

**Comment by shwestrick** [comment]
Thanks, I'll look into it.

**Comment by shwestrick** [comment]
I pushed some updates which fixes this issue by vertically aligning infix expressions.

The new output on your example looks like this:
```sml
fun main () =
  let
    val foo =
      "01234567890123456789012345678901234567890123456789"
      ^ "01234567890123456789012345678901234567890123456789"
      ^ "01234567890123456789012345678901234567890123456789"
  in
    print foo
  end
```

I think this is a decent solution for now, and it generally looks pretty good.

**Comment by dram** [comment]
Fix confirmed, nice work!
