### ISSUE TITLE
Support top-level expressions

### ISSUE THREAD

**Issue by p-ouellette** [shwestrick/parse-sml#57]
It's not in the Definition, but is supported by many compilers. This would be useful for formatting code that uses the `use` function.

**Comment by shwestrick** [comment]
Yeah this seems like it would be useful. Can you provide some examples?

My first thought is that special-casing a top-level `use` wouldn't be too bad. But full support for top-level expressions is probably a bit too much at the moment, since this tool doesn't do any type checking or evaluation.

**Comment by p-ouellette** [comment]
I only really care about the `use` case. Here's an example:
```
-- PARSE ERROR -----------------------------------------------------------------

Unexpected token.

t.sml
  |
1 | use "file.sml";
  | ^^^

Invalid start of top-level declaration.
```
However I don't really understand why parsing top-level expressions in general would require type checking.

**Comment by shwestrick** [comment]
Oh! My bad, I got confused thinking you wanted the `use ...` to load another file (to parse and format it).

Supporting top-level expressions in the parser + pretty printer seems like it shouldn't be too difficult. I'll take a shot at it.

**Comment by shwestrick** [comment]
Should be working now! Thanks for the suggestion.

**Comment by p-ouellette** [comment]
Thanks!
